language: android

sudo: required

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    - android-25

  licenses:
    - android-sdk-license-.+
    - '.+'

  cache:
    directories:
      - $HOME/.gradle/caches/2.8
      - $HOME/.gradle/caches/jars-1
      - $HOME/.gradle/daemon
      - $HOME/.gradle/native
      - $HOME/.gradle/wrapper

jdk:
  - oraclejdk8

script:
  - ./gradlew test

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"